"""M9 REGISTRATION — states, block codes, abstain codes, model types.

The M9 status is a state (SUCCESS / SUCCESS_WITH_WARNINGS / ABSTAIN /
BLOCKED / FAILED), never a numeric accuracy or a "winner". Registration
output is a declared geometric transform in the effective matcher plane
plus derived diagnostics — an observed geometric computation, never a
physical accuracy or geolocation claim.
"""

from __future__ import annotations

# final states (machine-readable)
SUCCESS = "SUCCESS"
SUCCESS_WITH_WARNINGS = "SUCCESS_WITH_WARNINGS"
ABSTAIN = "ABSTAIN"
BLOCKED = "BLOCKED"
FAILED = "FAILED"

STATUS_STATES = (SUCCESS, SUCCESS_WITH_WARNINGS, ABSTAIN, BLOCKED, FAILED)

# transitional state used only inside an in-flight run
RUNNING = "RUNNING"

# upstream states referenced by M9 resolution (never produced by M9)
SELECTED = "SELECTED"
SELECTED_WITH_WARNINGS = "SELECTED_WITH_WARNINGS"
M8_USABLE_STATES = (SELECTED, SELECTED_WITH_WARNINGS)

# block codes (stable, persisted)
M8_SELECTION_NOT_AVAILABLE = "M8_SELECTION_NOT_AVAILABLE"
REAL_DATA_BLOCKED = "REAL_DATA_BLOCKED"
PRODUCT_MISSING = "PRODUCT_MISSING"
INVALID_COORDINATE_FRAME = "INVALID_COORDINATE_FRAME"
INPUT_ARTIFACT_INVALID = "INPUT_ARTIFACT_INVALID"
UNKNOWN_CONFIG = "UNKNOWN_CONFIG"

BLOCK_CODES = (
    M8_SELECTION_NOT_AVAILABLE,
    REAL_DATA_BLOCKED,
    PRODUCT_MISSING,
    INVALID_COORDINATE_FRAME,
    INPUT_ARTIFACT_INVALID,
    UNKNOWN_CONFIG,
)

# abstain codes (stable, persisted)
INSUFFICIENT_SELECTED_POINTS = "INSUFFICIENT_SELECTED_POINTS"
DEGENERATE_GEOMETRY = "DEGENERATE_GEOMETRY"
NO_VALID_TRANSFORM = "NO_VALID_TRANSFORM"
RESOURCE_LIMIT = "RESOURCE_LIMIT"

ABSTAIN_CODES = (
    INSUFFICIENT_SELECTED_POINTS,
    DEGENERATE_GEOMETRY,
    NO_VALID_TRANSFORM,
    RESOURCE_LIMIT,
)

# failure codes (stable, persisted)
TRANSFORM_FIT_ERROR = "TRANSFORM_FIT_ERROR"
WARP_FAILED = "WARP_FAILED"
ARTIFACT_WRITE_FAILED = "ARTIFACT_WRITE_FAILED"

FAIL_CODES = (TRANSFORM_FIT_ERROR, WARP_FAILED, ARTIFACT_WRITE_FAILED)

# transform model types
AFFINE = "AFFINE"
HOMOGRAPHY = "HOMOGRAPHY"

MODEL_TYPES = (AFFINE, HOMOGRAPHY)

# transform selection reasons (smallest-valid-first policy)
SELECTION_REASON_SMALLEST_VALID = "SMALLEST_VALID_AFFINE"
SELECTION_REASON_AFFINE_ESCALATED = "AFFINE_INVALID_ESCALATED_HOMOGRAPHY"
SELECTION_REASON_EXPLICIT_HOMOGRAPHY = "EXPLICIT_HOMOGRAPHY"

SELECTION_REASONS = (
    SELECTION_REASON_SMALLEST_VALID,
    SELECTION_REASON_AFFINE_ESCALATED,
    SELECTION_REASON_EXPLICIT_HOMOGRAPHY,
)

# warning codes (recorded inside SUCCESS_WITH_WARNINGS)
WARP_INPUT_MISSING = "WARP_INPUT_MISSING"
WARP_OUTPUT_SKIPPED = "WARP_OUTPUT_SKIPPED"
SCALE_CHANGE_LARGE = "SCALE_CHANGE_LARGE"
SHEAR_ANISOTROPY = "SHEAR_ANISOTROPY"
NON_FINITE_POINTS_DROPPED = "NON_FINITE_POINTS_DROPPED"
DUPLICATE_POINTS_DROPPED = "DUPLICATE_POINTS_DROPPED"
HOLE_FILLED_VISUALIZATION = "HOLE_FILLED_VISUALIZATION"
BOUNDS_WARNED = "BOUNDS_WARNED"

WARNING_CODES = (
    WARP_INPUT_MISSING,
    WARP_OUTPUT_SKIPPED,
    SCALE_CHANGE_LARGE,
    SHEAR_ANISOTROPY,
    NON_FINITE_POINTS_DROPPED,
    DUPLICATE_POINTS_DROPPED,
    HOLE_FILLED_VISUALIZATION,
    BOUNDS_WARNED,
)


def tone(state: str) -> str:
    if state == SUCCESS:
        return "ok"
    if state in (SUCCESS_WITH_WARNINGS, ABSTAIN):
        return "warn"
    if state == BLOCKED:
        return "neutral"
    return "danger"