from __future__ import annotations

from enum import Enum


class TrustGateState(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    BLOCKED = "BLOCKED"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"


class TileTrustState(str, Enum):
    NOT_RUN = "NOT_RUN"
    RUNNING = "RUNNING"
    TRUSTED = "TRUSTED"
    REJECTED = "REJECTED"
    INSUFFICIENT = "INSUFFICIENT"
    FAILED = "FAILED"


class TrustBlockCode(str, Enum):
    MATCHING_NOT_AVAILABLE = "MATCHING_NOT_AVAILABLE"
    NO_CANDIDATE_ARTIFACT = "NO_CANDIDATE_ARTIFACT"
    PROCESSING_NOT_READY = "PROCESSING_NOT_READY"
    TRUST_UNKNOWN_CONFIG = "TRUST_UNKNOWN_CONFIG"
    TRUST_BLOCKED_PAIR = "TRUST_BLOCKED_PAIR"
    CANDIDATE_INTEGRITY_FAILED = "CANDIDATE_INTEGRITY_FAILED"


class TrustReasonCode(str, Enum):
    TG_PASS_CANDIDATE_INTEGRITY = "TG_PASS_CANDIDATE_INTEGRITY"
    TG_PASS_GEOMETRY = "TG_PASS_GEOMETRY"
    TG_PASS_INLIERS = "TG_PASS_INLIERS"
    TG_PASS_RESIDUAL_POLICY = "TG_PASS_RESIDUAL_POLICY"
    TG_PASS_SPATIAL_SUPPORT = "TG_PASS_SPATIAL_SUPPORT"
    TG_PASS_DEGENERACY_CHECKS = "TG_PASS_DEGENERACY_CHECKS"
    TG_PASS_CROSS_CHECK = "TG_PASS_CROSS_CHECK"
    TG_BLOCK_NO_CANDIDATES = "TG_BLOCK_NO_CANDIDATES"
    TG_BLOCK_INSUFFICIENT_USABLE = "TG_BLOCK_INSUFFICIENT_USABLE"
    TG_FAIL_MODEL_FIT_FAILED = "TG_FAIL_MODEL_FIT_FAILED"
    TG_FAIL_MODEL_INVALID = "TG_FAIL_MODEL_INVALID"
    TG_FAIL_DEGENERATE_GEOMETRY = "TG_FAIL_DEGENERATE_GEOMETRY"
    TG_FAIL_INSUFFICIENT_INLIERS = "TG_FAIL_INSUFFICIENT_INLIERS"
    TG_FAIL_LOW_INLIER_RATIO = "TG_FAIL_LOW_INLIER_RATIO"
    TG_FAIL_LOW_SPATIAL_SUPPORT = "TG_FAIL_LOW_SPATIAL_SUPPORT"
    TG_FAIL_EXCESSIVE_RESIDUAL = "TG_FAIL_EXCESSIVE_RESIDUAL"
    TG_FAIL_CROSS_CHECK = "TG_FAIL_CROSS_CHECK"
    TG_NOT_RUN = "TG_NOT_RUN"
