"""M1 real-data activation tests (PATH A).

These tests exercise the REAL-DATA intake path (source classification,
footprint-derived overlap, gate resolution, auto-registration, blocked
state) using REAL-SHAPED structure labels generated by fixturegen — written
only inside pytest tmp dirs, never committed, never usable as science.
"""

from __future__ import annotations

from pathlib import Path

import pytest

import fixturegen  # noqa: F401  (tests/ on sys.path via conftest)
from auth_helpers import authed_client_for_app, configure_auth


def _make_settings(tmp_path, settings_factory):
    """Settings whose data root equals the tmp dir that holds the fixtures."""
    return settings_factory(data_root=str(tmp_path))


def _api_harness(tmp_path):
    from backend.app.config import Settings
    from backend.app.data import ensure_derived_directories
    from backend.app.main import create_app

    settings = Settings(data_root=str(tmp_path), _env_file=None)
    ensure_derived_directories(settings)
    configure_auth(settings)
    app = create_app(settings=settings)
    return authed_client_for_app(app), settings


# --------------------------------------------------------------------------
# Source classification
# --------------------------------------------------------------------------

def test_real_shaped_label_classifies_real_pradan(tmp_path, settings_factory):
    from backend.app.loader import SOURCE_REAL_PRADAN, load_product

    files = fixturegen.write_real_shaped_pair(tmp_path)
    pa = load_product(files["ohrc_img"], files["ohrc_label"])
    pb = load_product(files["tmc2_img"], files["tmc2_label"])
    assert pa.status == "OK" and pb.status == "OK"
    assert pa.source_class == SOURCE_REAL_PRADAN
    assert pb.source_class == SOURCE_REAL_PRADAN
    assert str(pa.product_id).startswith("urn:isro:ch2")
    assert "bbox[" in pa.footprint
    assert pa.illumination_info.startswith("solar_zenith_angle=")
    assert pa.extra.get("orbit") == "8842"


def test_standard_fixture_still_classifies_test_fixture(tmp_path, settings_factory):
    from backend.app.loader import SOURCE_TEST_FIXTURE, load_product

    files = fixturegen.write_standard_fixtures(tmp_path)
    pa = load_product(files["ohrc_img"], files["ohrc_label"])
    pb = load_product(files["tmc2_img"], files["tmc2_label"])
    assert pa.source_class == SOURCE_TEST_FIXTURE
    assert pb.source_class == SOURCE_TEST_FIXTURE
    assert pa.footprint == "UNKNOWN"
    assert pa.viewing_geometry_info != "UNKNOWN" or True  # honoring honesty: no angles => UNKNOWN is fine


def test_load_without_label_is_unknown_source(tmp_path, settings_factory):
    from backend.app.loader import SOURCE_UNKNOWN, load_product

    files = fixturegen.write_standard_fixtures(tmp_path)
    info = load_product(files["ohrc_img"], None)
    assert info.source_class == SOURCE_UNKNOWN


# --------------------------------------------------------------------------
# Footprint-derived overlap
# --------------------------------------------------------------------------

def test_overlap_from_footprints_confirmed(tmp_path, settings_factory):
    from backend.app.loader import load_product
    from backend.app.pairs import overlap_from_footprints

    files = fixturegen.write_real_shaped_pair(tmp_path)
    pa = load_product(files["ohrc_img"], files["ohrc_label"])
    pb = load_product(files["tmc2_img"], files["tmc2_label"])
    status, evidence = overlap_from_footprints(pa, pb)
    assert status == "CONFIRMED_OVERLAP"
    assert "bbox_intersection" in evidence


def test_overlap_from_footprints_disjoint(tmp_path, settings_factory):
    from backend.app.loader import load_product
    from backend.app.pairs import overlap_from_footprints

    far = {"west": 60.0, "east": 60.6, "north": -5.0, "south": -5.6}
    files = fixturegen.write_real_shaped_pair(tmp_path, tmc2_bbox=far)
    pa = load_product(files["ohrc_img"], files["ohrc_label"])
    pb = load_product(files["tmc2_img"], files["tmc2_label"])
    status, evidence = overlap_from_footprints(pa, pb)
    assert status == "OVERLAP_UNCONFIRMED"
    assert "footprints_disjoint" in evidence


def test_overlap_from_footprints_missing_evidence(tmp_path, settings_factory):
    from backend.app.loader import load_product
    from backend.app.pairs import overlap_from_footprints

    files = fixturegen.write_standard_fixtures(tmp_path)
    pa = load_product(files["ohrc_img"], files["ohrc_label"])
    pb = load_product(files["tmc2_img"], files["tmc2_label"])
    status, evidence = overlap_from_footprints(pa, pb)
    assert status == "OVERLAP_UNCONFIRMED"
    assert evidence == "footprint_evidence_missing_on_one_side"


def test_data_gate_rules():
    from backend.app.pairs import data_gate

    assert data_gate("REAL_PRADAN", "REAL_PRADAN") == "PATH_A_REAL_DATA"
    assert data_gate("REAL_PRADAN", "TEST_FIXTURE") == "PATH_B_SYNTHETIC_ONLY"
    assert data_gate("TEST_FIXTURE", "TEST_FIXTURE") == "PATH_B_SYNTHETIC_ONLY"
    assert data_gate("REAL_PRADAN", "UNKNOWN") == "PATH_UNKNOWN"
    assert data_gate("UNKNOWN", "UNKNOWN") == "PATH_UNKNOWN"


# --------------------------------------------------------------------------
# Scan / select / register (real-data service)
# --------------------------------------------------------------------------

def test_scan_and_select_prefers_real_products(tmp_path, settings_factory):
    from backend.app.pairs import scan_raw_products, select_real_pair

    fixturegen.write_standard_fixtures(tmp_path)  # fixtures present too
    fixturegen.write_real_shaped_pair(tmp_path)   # real-shaped sources
    settings = _make_settings(tmp_path, settings_factory)

    inventory = scan_raw_products(settings)
    real = [e for e in inventory if e["source_class"] == "REAL_PRADAN"]
    assert len(real) >= 2

    ohrc, tmc2 = select_real_pair(settings)
    assert ohrc is not None and tmc2 is not None
    assert ohrc["instrument"] == "ohrc"
    assert tmc2["instrument"] == "tmc2"
    assert "urn:isro:ch2" in ohrc["product_id"]


def test_register_real_pair_is_gated_and_idempotent(tmp_path, settings_factory):
    from backend.app.pairs import PairRegistry, register_real_pair

    fixturegen.write_real_shaped_pair(tmp_path)
    settings = _make_settings(tmp_path, settings_factory)

    r1 = register_real_pair(
        settings, image_a_rel="raw/ohrc/ch2_ohr_ncp_20211228T2209123959_c_img_d18.img",
        image_b_rel="raw/tmc2/ch2_tmc_ncn_20200207T0716469418_c_img_d18.img",
    )
    assert r1.data_source_gate == "PATH_A_REAL_DATA"
    assert r1.source_class_a == "REAL_PRADAN"
    assert r1.source_class_b == "REAL_PRADAN"
    assert r1.overlap_status == "CONFIRMED_OVERLAP"
    assert r1.overlap_evidence.startswith("footprint_bbox_intersection")

    r2 = register_real_pair(
        settings, image_a_rel="raw/ohrc/ch2_ohr_ncp_20211228T2209123959_c_img_d18.img",
        image_b_rel="raw/tmc2/ch2_tmc_ncn_20200207T0716469418_c_img_d18.img",
    )
    assert r2.pair_id == r1.pair_id  # idempotent, not duplicated
    all_ids = [r.pair_id for r in PairRegistry(settings).list()]
    assert all_ids.count(r1.pair_id) == 1


def test_register_real_pair_rejects_fixtures(tmp_path, settings_factory):
    from backend.app.pairs import register_real_pair

    fixturegen.write_standard_fixtures(tmp_path)  # fixtures only
    settings = _make_settings(tmp_path, settings_factory)
    with pytest.raises(ValueError) as exc:
        register_real_pair(
            settings,
            image_a_rel="raw/ohrc/ch2_ohr_ncp_20211228T2209123959_d_img_d18.img",
            image_b_rel="raw/tmc2/ch2_tmc_ncn_20200207T0716469418_d_img_d18.img",
        )
    assert "REAL_PRADAN" in str(exc.value)


def test_validate_real_pair_record(tmp_path, settings_factory):
    from backend.app.pairs import PairRegistry, register_real_pair, validate_record

    fixturegen.write_real_shaped_pair(tmp_path)
    settings = _make_settings(tmp_path, settings_factory)
    record = register_real_pair(
        settings, image_a_rel="raw/ohrc/ch2_ohr_ncp_20211228T2209123959_c_img_d18.img",
        image_b_rel="raw/tmc2/ch2_tmc_ncn_20200207T0716469418_c_img_d18.img",
    )
    result = validate_record(record, settings)
    assert result["status"] == "VALID"
    assert result["raw_integrity"] == "VERIFIED"
    assert result["overlap"]["benchmark_ready"] is True
    reg = PairRegistry(settings)
    assert reg.get(record.pair_id).data_source_gate == "PATH_A_REAL_DATA"


# --------------------------------------------------------------------------
# API surface
# --------------------------------------------------------------------------

def test_api_auto_register_real_pair(tmp_path):
    client, settings = _api_harness(tmp_path)
    fixturegen.write_real_shaped_pair(tmp_path)

    r = client.post("/api/pairs/auto-register", json={})
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["registered"] is True
    assert body["gate"] == "PATH_A_REAL_DATA"
    assert body["validation"]["status"] == "VALID"

    scan = client.get("/api/pairs/real-data/scan")
    assert scan.status_code == 200
    scan_body = scan.json()
    assert scan_body["source_breakdown"]["REAL_PRADAN"] == 2
    assert scan_body["selected_ohrc"] is not None
    assert scan_body["selected_tmc2"] is not None

    root_status = client.get("/api/data/status")
    assert root_status.status_code == 200
    ds = root_status.json()["data_source"]
    assert ds["requirements_met"] is True
    assert body["pair_id"] in ds["registered_real_pair_ids"]


def test_api_auto_register_blocked_honestly(tmp_path):
    client, _settings = _api_harness(tmp_path)
    fixturegen.write_standard_fixtures(tmp_path)  # fixtures only

    r = client.post("/api/pairs/auto-register", json={})
    assert r.status_code == 400, r.text
    body = r.json()
    assert body["error"]["details"]["blocked"] is True
    assert "blocked" in body["error"]["message"]


def test_data_status_source_breakdown_honest_on_empty(tmp_path):
    client, _settings = _api_harness(tmp_path)
    body = client.get("/api/data/status").json()["data_source"]
    assert body["source_breakdown"] == {"REAL_PRADAN": 0, "TEST_FIXTURE": 0, "UNKNOWN": 0}
    assert body["requirements_met"] is False