"""M7 Trust Gate decision + block codes (final state machine)."""

from __future__ import annotations

ACCEPT = "ACCEPT"
REJECT = "REJECT"
ABSTAIN = "ABSTAIN"
BLOCKED = "BLOCKED"

DECISION_STATES = (ACCEPT, REJECT, ABSTAIN, BLOCKED)

# Block / abort codes (stable, persisted)
PROCESSING_NOT_RUN = "PROCESSING_NOT_RUN"
MATCH_RUN_NOT_AVAILABLE = "MATCH_RUN_NOT_AVAILABLE"
PRODUCT_MISSING = "PRODUCT_MISSING"
CANDIDATES_MISSING = "CANDIDATES_MISSING"
INVALID_COORDINATE_FRAME = "INVALID_COORDINATE_FRAME"
INVALID_INPUT = "INVALID_INPUT"
REAL_DATA_BLOCKED = "REAL_DATA_BLOCKED"
TRUST_ESTIMATION_FAILED = "TRUST_ESTIMATION_FAILED"
RESOURCE_LIMIT = "RESOURCE_LIMIT"

BLOCK_CODES = (
    PROCESSING_NOT_RUN,
    MATCH_RUN_NOT_AVAILABLE,
    PRODUCT_MISSING,
    CANDIDATES_MISSING,
    INVALID_COORDINATE_FRAME,
    INVALID_INPUT,
    REAL_DATA_BLOCKED,
    TRUST_ESTIMATION_FAILED,
    RESOURCE_LIMIT,
)

# Abstain reason codes (stable, persisted)
ZERO_CANDIDATES = "ZERO_CANDIDATES"
INSUFFICIENT_CANDIDATES = "INSUFFICIENT_CANDIDATES"
DEGENERATE_GEOMETRY = "DEGENERATE_GEOMETRY"
NO_VALID_MODEL = "NO_VALID_MODEL"

# Reject reason codes (stable, persisted)
INSUFFICIENT_INLIERS = "INSUFFICIENT_INLIERS"
LOW_INLIER_RATIO = "LOW_INLIER_RATIO"
RESIDUAL_EXCEEDED = "RESIDUAL_EXCEEDED"
SPATIAL_SANITY_FAILED = "SPATIAL_SANITY_FAILED"
MODEL_INVALID = "MODEL_INVALID"

# Spatial sanity states
SPATIAL_PASS = "PASS"
SPATIAL_WARN = "WARN"
SPATIAL_FAIL = "FAIL"


def decision_tone(state: str) -> str:
    if state == ACCEPT:
        return "ok"
    if state == REJECT:
        return "danger"
    if state == ABSTAIN:
        return "warn"
    return "neutral"