"""M5 state + reason-code vocabulary for spatial reliability.

Binary, measurable, explainable outcomes. Nothing here claims scientific
confidence — the vocabulary distinguishes analysis state, mapping state,
cell evidence and selection reasons.
"""

from __future__ import annotations

from enum import Enum


class SpatialRunState(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    BLOCKED = "BLOCKED"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    INSUFFICIENT = "INSUFFICIENT"


class SpatialBlockCode(str, Enum):
    MATCHING_NOT_AVAILABLE = "MATCHING_NOT_AVAILABLE"
    TRUST_OUTPUTS_MISSING = "TRUST_OUTPUTS_MISSING"
    M4_NOT_AVAILABLE = "M4_NOT_AVAILABLE"
    NO_TRUSTED_EVIDENCE = "NO_TRUSTED_EVIDENCE"
    SPATIAL_MAPPING_UNAVAILABLE = "SPATIAL_MAPPING_UNAVAILABLE"
    SPATIAL_UNKNOWN_CONFIG = "SPATIAL_UNKNOWN_CONFIG"
    SPATIAL_INVALID_ARTIFACT = "SPATIAL_INVALID_ARTIFACT"
    SPATIAL_TIMEOUT = "SPATIAL_TIMEOUT"


class MappingStatus(str, Enum):
    MAPPED = "MAPPED"
    NOT_MAPPABLE = "NOT_MAPPABLE"


class MappingReason(str, Enum):
    MAP_OK = "MAPPED_OK"
    MISSING_OVERLAP_GEOMETRY = "MISSING_OVERLAP_GEOMETRY"
    ZERO_AREA_OVERLAP = "ZERO_AREA_OVERLAP"
    MISSING_TILE_GEOMETRY = "MISSING_TILE_GEOMETRY"
    UNKNOWN_TILE_ORIGIN = "UNKNOWN_TILE_ORIGIN"
    MISSING_TILE_DIMENSIONS = "MISSING_TILE_DIMENSIONS"
    TILE_NOT_MAPPED_TO_TWO_SIDES = "TILE_NOT_MAPPED_TO_TWO_SIDES"
    NON_FINITE_COORDINATES = "NON_FINITE_COORDINATES"
    OUT_OF_SCENE = "OUT_OF_SCENE"


class SelectionReasonCode(str, Enum):
    SR_SELECTED_SUPPORTED_REGION = "SR_SELECTED_SUPPORTED_REGION"
    SR_SELECTED_SPATIAL_COVERAGE = "SR_SELECTED_SPATIAL_COVERAGE"
    SR_SELECTED_NEIGHBOR_SUPPORTED = "SR_SELECTED_NEIGHBOR_SUPPORTED"
    SR_EXCLUDED_NOT_TRUSTED = "SR_EXCLUDED_NOT_TRUSTED"
    SR_EXCLUDED_LOW_SPATIAL_SUPPORT = "SR_EXCLUDED_LOW_SPATIAL_SUPPORT"
    SR_EXCLUDED_ISOLATED = "SR_EXCLUDED_ISOLATED"
    SR_EXCLUDED_OUTSIDE_SELECTED_REGION = "SR_EXCLUDED_OUTSIDE_SELECTED_REGION"
    SR_EXCLUDED_BOUNDARY_POLICY = "SR_EXCLUDED_BOUNDARY_POLICY"
    SR_EXCLUDED_LIMIT = "SR_EXCLUDED_LIMIT"
    SR_NOT_MAPPABLE = "SR_NOT_MAPPABLE"
    SR_NOT_RUN = "SR_NOT_RUN"