"""M8 SPATIAL SELECTION — states, warning codes, block codes.

The M8 status is a state (SELECTED / SELECTED_WITH_WARNINGS / ABSTAIN /
BLOCKED / FAILED), never a numeric confidence or a "winner".
"""

from __future__ import annotations

# final states
SELECTED = "SELECTED"
SELECTED_WITH_WARNINGS = "SELECTED_WITH_WARNINGS"
ABSTAIN = "ABSTAIN"
BLOCKED = "BLOCKED"
FAILED = "FAILED"

STATUS_STATES = (SELECTED, SELECTED_WITH_WARNINGS, ABSTAIN, BLOCKED, FAILED)

# trusted-gate states referenced by M8 resolution (never produced by M8)
ACCEPT = "ACCEPT"

# warning codes (stable, persisted)
CONCENTRATED_SOURCE = "CONCENTRATED_SOURCE"
CONCENTRATED_TARGET = "CONCENTRATED_TARGET"
LOW_SOURCE_COVERAGE = "LOW_SOURCE_COVERAGE"
LOW_TARGET_COVERAGE = "LOW_TARGET_COVERAGE"
FEW_OCCUPIED_CELLS = "FEW_OCCUPIED_CELLS"
SELECTION_LIMIT_APPLIED = "SELECTION_LIMIT_APPLIED"
BOUNDARY_POINTS_REPORTED = "BOUNDARY_POINTS_REPORTED"

WARNING_CODES = (
    CONCENTRATED_SOURCE,
    CONCENTRATED_TARGET,
    LOW_SOURCE_COVERAGE,
    LOW_TARGET_COVERAGE,
    FEW_OCCUPIED_CELLS,
    SELECTION_LIMIT_APPLIED,
    BOUNDARY_POINTS_REPORTED,
)

# block codes (stable, persisted)
NO_TRUST_RUN = "NO_TRUST_RUN"
TRUST_NOT_ACCEPTED = "TRUST_NOT_ACCEPTED"
TRUST_PAIR_MISMATCH = "TRUST_PAIR_MISMATCH"
MATCH_RUN_UNRECOVERABLE = "MATCH_RUN_UNRECOVERABLE"
NONDETERMINISTIC_RECOVERY = "NONDETERMINISTIC_RECOVERY"
INVALID_COORDINATE_FRAME = "INVALID_COORDINATE_FRAME"
REAL_DATA_BLOCKED = "REAL_DATA_BLOCKED"
INVALID_INPUT = "INVALID_INPUT"
INVALID_RECOVERY_STATE = "INVALID_RECOVERY_STATE"

BLOCK_CODES = (
    NO_TRUST_RUN,
    TRUST_NOT_ACCEPTED,
    TRUST_PAIR_MISMATCH,
    MATCH_RUN_UNRECOVERABLE,
    NONDETERMINISTIC_RECOVERY,
    INVALID_COORDINATE_FRAME,
    REAL_DATA_BLOCKED,
    INVALID_INPUT,
    INVALID_RECOVERY_STATE,
)

# abstain codes (stable, persisted)
ZERO_TRUSTED = "ZERO_TRUSTED"
FEW_TRUSTED = "FEW_TRUSTED"
NO_VALID_SELECTION = "NO_VALID_SELECTION"
RESOURCE_LIMIT = "RESOURCE_LIMIT"

ABSTAIN_CODES = (ZERO_TRUSTED, FEW_TRUSTED, NO_VALID_SELECTION, RESOURCE_LIMIT)

# abstain theme used by service for recovery-result states
RECOVERY_OK = "RECOVERY_OK"
RECOVERY_ABSTAIN = "RECOVERY_ABSTAIN"
RECOVERY_BLOCKED = "RECOVERY_BLOCKED"


def tone(state: str) -> str:
    if state in (SELECTED,):
        return "ok"
    if state in (SELECTED_WITH_WARNINGS, ABSTAIN):
        return "warn"
    if state == BLOCKED:
        return "neutral"
    return "danger"